class CreditCardIssuers {

    Company company
    Contact contact
    String AAtotalOPENcardholderAccounts
    String ABtotalACTIVEcardholderAccounts
    String ACtotalChargeVolume
    String ADtotalVISAcardsIssued
    String AEtotalMasterCardcardsIssued
    String AFtotalAmericaExpresscardsIssued
    String AGtotalDiscovercardsIssued
    String AHtotalJCBcardsIssued
    String AIaffinityCo_brandedCardPrograms
    String AJaffinityCo_brandedProgram1
    String AKaffinityCo_brandedProgram2
    String ALaffinityCo_brandedProgram3
    String AMaffinityCo_brandedProgram4
    String ANaffinityCo_brandedProgram5
    String AOVISAaffinityCo_brandedCards
    String APMasterCardaffinityCo_brandedCards
    String AQAmericanExpressaffinityCo_brandedCards
    String ARDiscoveraffinityCo_brandedCards
    String AScreditCardTransProcessor
    boolean ATcontactlessCreditCards
    String AUNumcontactlessCreditCards
    String AUNumcontactlessCreditCardTrans
    String AVtotalChargeVolumeContactlessPurchases
    String AWcontactlessCreditCardBrand1
    String AXcontactlessCreditCardBrand2
    String AYformFactor1
    String AZformFactor2
    String BAformFactor3
    String executiveFirstName1
    String executiveLastName1
    String executiveEmail1
    String executiveTitle1
    String executiveDept1
    String executiveFirstName2
    String executiveLastName2
    String executiveEmail2
    String executiveTitle2
    String executiveDept2
    String executiveFirstName3
    String executiveLastName3
    String executiveEmail3
    String executiveTitle3
    String executiveDept3
    String executiveFirstName4
    String executiveLastName4
    String executiveEmail4
    String executiveTitle4
    String executiveDept4
    String executiveFirstName5
    String executiveLastName5
    String executiveEmail5
    String executiveTitle5
    String executiveDept5
    Date createDate
    Date updateDate
}
