class CreditCardIssuers {
    Company company
    Contact contact
    String AAtotalOPENcardholderAccounts
    String ABtotalACTIVEcardholderAccounts
    String ACtotalChargeVolume
    String ADtotalVISAcardsIssued
    String AEtotalMasterCardcardsIssued
    String AFtotalAmericaExpresscardsIssued
    String AGtotalDiscovercardsIssued
    String AHtotalJCBcardsIssued
    String AIaffinityCo_brandedCardPrograms
    String AJaffinityCo_brandedProgram1
    String AKaffinityCo_brandedProgram2
    String ALaffinityCo_brandedProgram3
    String AMaffinityCo_brandedProgram4
    String ANaffinityCo_brandedProgram5
    String AOVISAaffinityCo_brandedCards
    String APMasterCardaffinityCo_brandedCards
    String AQAmericanExpressaffinityCo_brandedCards
    String ARDiscoveraffinityCo_brandedCards
    String AScreditCardTransProcessor
    boolean ATcontactlessCreditCards
    String AUNumcontactlessCreditCards
    String AVtotalChargeVolumeContactlessPurchases
    String AWcontactlessCreditCardBrand1
    String AXcontactlessCreditCardBrand2
    String AYformFactor1
    String AZformFactor2
    String BAformFactor3
    String executiveName1
    String executiveTitle1
    String executiveDept1
    String executiveName2
    String executiveTitle2
    String executiveDept2
    String executiveName3
    String executiveTitle3
    String executiveDept3
    String executiveName4
    String executiveTitle4
    String executiveDept4
    String executiveName5
    String executiveTitle5
    String executiveDept5
    Date createDate
    Date updateDate
}
